version: "3"

services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServer
    volumes:
      - sqlServeDev:/var/opt/mssql
    ports:
      - "1401:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      
  sql-server-test:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServerTest    
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"

  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      PUID: "1000"
      PGID: "1000"
  
volumes:
  sqlServeDev:

      