version: "3"

services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: SqlServer
    volumes:
      - ../../sqlServerVolume:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"

  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      PUID: "1000"
      PGID: "1000"
      